version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./src:/var/www
    links:
      - db
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    ports:
      - "80:80"
      - "443:443"
  
  db:
    build:
      context: ./database
    ports: 
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql
  php-myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db

  


  